server.port=9090

# Telegram API
telegram.api.url=https://api.telegram.org/bot
telegram.bot.id=8629522001:AAGLESYqPyDKE3iE7vA294q5DWvx7G7qijw

#OpenWeatherMap
open.weather.api.url=https://api.openweathermap.org/data/2.5/weather
open.weather.api.token=cd808a123e23e24fba9093e20b9e456d

# Blagues API
blagues.api.url=https://www.blagues-api.fr/api/type/dark/random
blagues.api.token=${BLAGUES_API_TOKEN:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMzU3MTkyMTAxMjM2MTc4OTQ1IiwibGltaXQiOjEwMCwia2V5IjoiZDJNUHNsTFJCRnkycm5CMXo1Q1FwYXA2b3FTOG9PY21XbVhuRTdQR3pSUGFOVTFOUlAiLCJjcmVhdGVkX2F0IjoiMjAyNi0wNS0xMVQwOTo0ODo1MSswMDowMCIsImlhdCI6MTc3ODQ5MjkzMX0.ULH65doaXJuijbXtP_fM2OZMt2wgk5DDOBBNNF8CYlg}

# Grok API
grok.api.url=https://api.groq.com/openai/v1/chat/completions
grok.api.token=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
