server.port=9090

# Telegram API
telegram.api.url=https://api.telegram.org/bot
telegram.bot.id=8629522001:AAGLESYqPyDKE3iE7vA294q5DWvx7G7qijw

#OpenWeatherMap
open.weather.api.url=https://api.openweathermap.org/data/2.5/weather
open.weather.api.token=cd808a123e23e24fba9093e20b9e456d

